### ISSUE TITLE
perf[nonnative]: optimise emulated arithmetic

### ISSUE THREAD

**Issue by ivokub** [ConsenSys/gnark#315]
- [x] most of the constraints come from the `assertLimbsEqualitySlow` method. We do not implement the limb grouping introduced in xjSnark and used in bellperson and arkworks libraries. It is fairly straightforward to implement, but I'm thinking about ways to optimise further #320 
- [x] in the same method, we can optimise for PLONK by doing unconstrained bit decomposition and comparing against zeros. For R1CS it is the same constraint count but should halve the number of constraints for PLONK. #320 
- [x] check that it is possible to perform several multiplications before needing to reduce. It should theoretically be possible but I am not sure if it works. #320
