### ISSUE TITLE
feat: zk-evm precompiles 

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#466]
Each of the precompile generated through gnark frontend should have:

* clean function signature that matches what's expected in the inner prover
* a constraint count with PlonK+bypassing the range checks, and PlonK+with api.Commit() enabled range checks.

- [ ] Pairing
- [ ] ECMul
- [ ] ECAdd
- [ ] Modexp
- [ ] ECRecover
- [ ] Sha256

**Comment by yelhousni** [comment]
After Pectra upgrade we should add to `evmprecompiles` package the following:
- [ ] Pairing on BLS12-381: #1368
- [ ] ECMul on BLS12-381 #1366
- [ ] ECAdd on BLS12-381 #1367
